Repository DataDog/pprof-format, pull requests merged in 2022-11, with the labels that each got.

#2 Make open-source-ready
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .gitignore
  CONTRIBUTING.md
  LICENSE
  LICENSE-3rdparty.csv
  NOTICE
  example.js
  package.json
  src/index.mts
  src/index.test.ts
  src/index.ts
Labels: documentation

#3 Add our universal/shared workflows
  .github/workflows/package-size.yml
  .github/workflows/pr-labels.yml
  .github/workflows/release.yml
Labels: semver-patch

#4 Setup CodeQL analysis
  .github/workflows/codeql.yml
Labels: semver-patch

#5 Fix off-by-one error in string table
  src/index.test.ts
  src/index.ts
Labels: bug, semver-major

#7 Fix end of slice computation for value when size is encoded on more than one byte
  src/index.test.ts
  src/index.ts
Labels: bug, semver-patch

#8 Comments field should be encoded and decoded as a packed repeated field
  src/index.test.ts
  src/index.ts
Labels: semver-patch
